export const Constants = {
    "dummyText" :"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it "
}

export const appMessages = {
    offline: "Your internet connection appears to be offline. Please try again.",
    // 401 message
    messageStatus401: "The user is not authorized to make the request.",
    messageStatus500: "Something went wrong.",
    resetLinkExpired: "Your password reset link has expired",
    clickBelow: "Click below to generate a new one.",
    wrongPage: "Sorry, we couldn't' find this page",
    tryAgain: "Try again searching or go to",
  };

export const apiConstants = {
    // Clear state
    CLEAR_STATE: "CLEAR_STATE",
    HANDLE_SIDEBAR_NAVIGATION_STATE: "HANDLE_SIDEBAR_NAVIGATION_STATE",
    HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE: "HANDLE_SIDEBAR_DRAWER_TOGGLE_STATE",
  
    // ************ AUTHENTICATION ************
    // Authentications types
    API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",
    API_AUTHENTICATION_ERROR: "API_AUTHENTICATION_ERROR",
  
    // Login
    API_LOGIN_LOAD: "API_LOGIN_LOAD",
    API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
  
    API_SIGNUP_LOAD: "API_SIGNUP_LOAD",
    API_SIGNUP_SUCCESS: "API_SIGNUP_SUCCESS",
  
    // Forgot Password
    API_FORGOT_PASSWORD_LOAD: "API_FORGOT_PASSWORD_LOAD",
    API_FORGOT_PASSWORD_SUCCESS: "API_FORGOT_PASSWORD_SUCCESS",
  
    // Reset Password
    API_RESET_PASSWORD_LOAD: "API_RESET_PASSWORD_LOAD",
    API_RESET_PASSWORD_SUCCESS: "API_RESET_PASSWORD_SUCCESS",
  
    // Reset Password
    API_CHECK_RESET_PASSWORD_LOAD: "API_CHECK_RESET_PASSWORD_LOAD",
    API_CHECK_RESET_PASSWORD_SUCCESS: "API_CHECK_RESET_PASSWORD_SUCCESS",
  
    // ************ USER MANAGEMENT ************
    // User Management
    API_USER_MANAGEMENT_FAILED: "API_USER_MANAGEMENT_FAILED",
    API_USER_MANAGEMENT_ERROR: "API_USER_MANAGEMENT_ERROR",
  
    //Get User List
    API_GET_USER_LIST_LOAD: "API_GET_USER_LIST_LOAD",
    API_GET_USER_LIST_SUCCESS: "API_GET_USER_LIST_SUCCESS",
  
    //Get User Details
    API_GET_USER_DETAILS_LOAD: "API_GET_USER_DETAILS_LOAD",
    API_GET_USER_DETAILS_SUCCESS: "API_GET_USER_DETAILS_SUCCESS",
  
    //Edit User Details
    API_EDIT_USER_DETAILS_LOAD: "API_EDIT_USER_DETAILS_LOAD",
    API_EDIT_USER_DETAILS_SUCCESS: "API_EDIT_USER_DETAILS_SUCCESS",
  
    //Block User
    API_BLOCK_USER_LOAD: "API_BLOCK_USER_LOAD",
    API_BLOCK_USER_SUCCESS: "API_BLOCK_USER_SUCCESS",
  
    // ************ TERMINAL AREA MANAGEMENT ************
    // Terminal Area Management Fail
    API_TERMINAL_AREA_MANAGEMENT_FAILED: "API_TERMINAL_AREA_MANAGEMENT_FAILED",
    API_TERMINAL_AREA_MANAGEMENT_ERROR: "API_TERMINAL_AREA_MANAGEMENT_ERROR",
  
    //Get Terminal Area List
    API_GET_TERMINAL_AREA_LIST_LOAD: "API_GET_TERMINAL_AREA_LIST_LOAD",
    API_GET_TERMINAL_AREA_LIST_SUCCESS: "API_GET_TERMINAL_AREA_LIST_SUCCESS",
  
    //Get Terminal Area Details
    API_GET_TERMINAL_AREA_DETAILS_LOAD: "API_GET_TERMINAL_AREA_DETAILS_LOAD",
    API_GET_TERMINAL_AREA_DETAILS_SUCCESS:
      "API_GET_TERMINAL_AREA_DETAILS_SUCCESS",
  
    //Add Terminal Area
    API_ADD_TERMINAL_AREA_LOAD: "API_ADD_TERMINAL_AREA_LOAD",
    API_ADD_TERMINAL_AREA_SUCCESS: "API_ADD_TERMINAL_AREA_SUCCESS",
  
    //Edit Terminal Area
    API_EDIT_TERMINAL_AREA_LOAD: "API_EDIT_TERMINAL_AREA_LOAD",
    API_EDIT_TERMINAL_AREA_SUCCESS: "API_EDIT_TERMINAL_AREA_SUCCESS",
  
    //Delete Terminal Area
    API_DELETE_TERMINAL_AREA_LOAD: "API_DELETE_TERMINAL_AREA_LOAD",
    API_DELETE_TERMINAL_AREA_SUCCESS: "API_DELETE_TERMINAL_AREA_SUCCESS",
  
    // ************ TERMINAL MANAGEMENT ************
  
    // Terminal Management Fail
    API_TERMINAL_MANAGEMENT_FAILED: "API_TERMINAL_MANAGEMENT_FAILED",
    API_TERMINAL_MANAGEMENT_ERROR: "API_TERMINAL_MANAGEMENT_ERROR",
  
    //Get Teminal List
    API_GET_TERMINAL_LIST_LOAD: "API_GET_TERMINAL_LIST_LOAD",
    API_GET_TERMINAL_LIST_SUCCESS: "API_GET_TERMINAL_LIST_SUCCESS",
  
    //Add Teminal
    API_ADD_TERMINAL_LOAD: "API_ADD_TERMINAL_LOAD",
    API_ADD_TERMINAL_SUCCESS: "API_ADD_TERMINAL_SUCCESS",
  
    //Get Teminal Details
    API_GET_TERMINAL_DETAILS_LOAD: "API_GET_TERMINAL_DETAILS_LOAD",
    API_GET_TERMINAL_DETAILS_SUCCESS: "API_GET_TERMINAL_DETAILS_SUCCESS",
  
    //Edit Teminal
    API_EDIT_TERMINAL_LOAD: "API_EDIT_TERMINAL_LOAD",
    API_EDIT_TERMINAL_SUCCESS: "API_EDIT_TERMINAL_SUCCESS",
  
    //Delete Teminal
    API_DELETE_TERMINAL_LOAD: "API_DELETE_TERMINAL_LOAD",
    API_DELETE_TERMINAL_SUCCESS: "API_DELETE_TERMINAL_SUCCESS",
  
    // ************ IMPORT / EXPORT FILE************
  
    //Import Teminal
    API_IMPORT_FILE_LOAD: "API_IMPORT_FILE_LOAD",
    API_IMPORT_FILE_SUCCESS: "API_IMPORT_FILE_SUCCESS",
  
    //Export Terminal files
    API_EXPORT_FILE_LOAD: "API_EXPORT_FILE_LOAD",
    API_EXPORT_FILE_SUCCESS: "API_EXPORT_FILE_SUCCESS",
  
    // ************ REPORT POST MANAGEMENT ************
  
    // Report Post Fail
    API_REPORT_POST_FAILED: "API_REPORT_POST_FAILED",
    API_REPORT_POST_ERROR: "API_REPORT_POST_ERROR",
  
    //Get Report Post List
    API_GET_REPORT_POST_LIST_LOAD: "API_GET_REPORT_POST_LIST_LOAD",
    API_GET_REPORT_POST_LIST_SUCCESS: "API_GET_REPORT_POST_LIST_SUCCESS",
  
    //Get Report Post Details
    API_GET_REPORT_POST_DETAILS_LOAD: "API_GET_REPORT_POST_DETAILS_LOAD",
    API_GET_REPORT_POST_DETAILS_SUCCESS: "API_GET_REPORT_POST_DETAILS_SUCCESS",
  
    //Delete Report Post
    API_DELETE_REPORT_POST_LOAD: "API_DELETE_REPORT_POST_LOAD",
    API_DELETE_REPORT_POST_SUCCESS: "API_DELETE_REPORT_POST_SUCCESS",
  
    //Revoke Report Post
    API_REVOKE_REPORT_POST_LOAD: "API_REVOKE_REPORT_POST_LOAD",
    API_REVOKE_REPORT_POST_SUCCESS: "API_REVOKE_REPORT_POST_SUCCESS",
  
    // ************ TERMINAL REPORT POST MANAGEMENT ************
  
    // Terminal Report Post Fail
    API_TERMINAL_REPORT_POST_FAILED: "API_TERMINAL_REPORT_POST_FAILED",
    API_TERMINAL_REPORT_POST_ERROR: "API_TERMINAL_REPORT_POST_ERROR",
  
    //Get Terminal Report Post List
    API_GET_TERMINAL_REPORT_POST_LIST_LOAD:
      "API_GET_TERMINAL_REPORT_POST_LIST_LOAD",
    API_GET_TERMINAL_REPORT_POST_LIST_SUCCESS:
      "API_GET_TERMINAL_REPORT_POST_LIST_SUCCESS",
  
    //Get Terminal Report Post Details
    API_GET_TERMINAL_REPORT_POST_DETAILS_LOAD:
      "API_GET_TERMINAL_REPORT_POST_DETAILS_LOAD",
    API_GET_TERMINAL_REPORT_POST_DETAILS_SUCCESS:
      "API_GET_TERMINAL_REPORT_POST_DETAILS_SUCCESS",
  
    //Delete Terminal Report Post
    API_DELETE_TERMINAL_REPORT_POST_LOAD: "API_DELETE_TERMINAL_REPORT_POST_LOAD",
    API_DELETE_TERMINAL_REPORT_POST_SUCCESS:
      "API_DELETE_TERMINAL_REPORT_POST_SUCCESS",
  
    // ************ IMAGE MANAGEMENT ************
  
    // Image Fail
    API_IMAGE_MANAGEMENT_FAILED: "API_IMAGE_MANAGEMENT_FAILED",
    API_IMAGE_MANAGEMENT_ERROR: "API_IMAGE_MANAGEMENT_ERROR",
  
    //Get Image List
    API_GET_IMAGE_LIST_LOAD: "API_GET_IMAGE_LIST_LOAD",
    API_GET_IMAGE_LIST_SUCCESS: "API_GET_IMAGE_LIST_SUCCESS",
  
    //Get Image Details
    API_ADD_IMAGE_LOAD: "API_ADD_IMAGE_LOAD",
    API_ADD_IMAGE_SUCCESS: "API_ADD_IMAGE_SUCCESS",
  
    //Delete Image
    API_DELETE_IMAGE_LOAD: "API_DELETE_IMAGE_LOAD",
    API_DELETE_IMAGE_SUCCESS: "API_DELETE_IMAGE_SUCCESS",
  
    // ************ SAVE USER LOCATION ************
  
    // Terminal Report Post Fail
    API_SAVED_USER_LOCATIONS_FAILED: "API_SAVED_USER_LOCATIONS_FAILED",
    API_SAVED_USER_LOCATIONS_ERROR: "API_SAVED_USER_LOCATIONS_ERROR",
  
    //Get Terminal Report Post List
    API_SAVED_USER_LOCATIONS_LOAD: "API_SAVED_USER_LOCATIONS_LOAD",
    API_SAVED_USER_LOCATIONS_SUCCESS: "API_SAVED_USER_LOCATIONS_SUCCESS",
  
    // ************ TIMELINE DETAILS ************
  
    //Get Timeline Details
    API_TIMELINE_DETAILS_LOAD: "API_TIMELINE_DETAILS_LOAD",
    API_TIMELINE_DETAILS_SUCCESS: "API_TIMELINE_DETAILS_SUCCESS",
  
    // ************ GEOFENCING ************
    // Geofencing Fail
    API_GEOFENCING_FAILED: "API_GEOFENCING_FAILED",
    API_GEOFENCING_ERROR: "API_GEOFENCING_ERROR",
  
    //Get Geofencing Details
    API_POST_GEOFENCING_LOAD: "API_POST_GEOFENCING_LOAD",
    API_POST_GEOFENCING_SUCCESS: "API_POST_GEOFENCING_SUCCESS",
  
    //radar management
  
    //radar management fail
    API_RADAR_MANAGEMENT_FAILED: "API_RADAR_MANAGEMENT_FAILED",
    API_RADAR_MANAGEMENT_ERROR: "API_RADAR_MANAGEMENT_ERROR",
  
    //get radar entry/exit list
    API_RADAR_ENTRY_EXIT_LOAD: "API_RADAR_ENTRY_EXIT_LOAD",
    API_RADAR_ENTRY_EXIT_SUCCESS: "API_RADAR_ENTRY_EXIT_SUCCESS",
  
    //get radar export list
    API_RADAR_EXPORT_LOAD: "API_RADAR_EXPORT_LOAD",
    API_RADAR_EXPORT_SUCCESS: "API_RADAR_EXPORT_SUCCESS",
  };

 